\section{Artihmetisches Mittel}
Das arithmetische Mittel beschreibt den Mittelwert der Summe aller Elemente.

\[ \bar{x} = \frac{1}{n} \sum\limits_{i=1}^{n} x_i \]

\subsection{R-Tipps}
\subsubsection{Zahlenfolgen definieren}
Vektor für eine lineare Zahlenfolge definieren mit Intervall = 1
<<>>=
x <- 1:10
x
@
Vektor für eine Zahlenfolge mit beliebigem Intervall (z.B. 3)
<<>>=
x <- seq(1,20,3)
x
@
Eine spezielle Zahlenfolge kann auch manuell definiert werden
<<>>=
x <- c(3,2,5,8,9,10,55,1,12)
x
@
\subsubsection{Artihmetisches Mittel mit R berechnen}
Mit R kann das arithmetische Mittel mit der Funktion \verb!mean()! 
ermittelt werden
<<>>=
x <- c(2,5,1,7,8,9)
mean(x)
@

\section{Standardabweichung}
Die Standardabweichung beschreibt wie gross die mittlere Abweichung der
Beobachtungen vom arithmetischen Mittel derselben Beobachtungen ist.
\[ s_x = \sqrt{ \frac{1}{n-1} \sum\limits_{i=1}^{n} (x_i - \bar{x})^2 } \]
Bsp.: Wir nehmen eine zufällige Zahlenfolge innerhalb $(1,10)$ und
rechnen das arithmetische Mittel als auch die Standardabweichung (\verb!sd()!).
<<>>=
x <- round(x=runif(n=10, min=1, max=10), digits=0)
x
mean(x)
sd(x)
@

\section{Quantile}
Quantile beschreiben folgenden Zusammenhang: Hat man z.B. 20 Messungen gemacht
und sortiert diese, dann beschreibt ein x\%-iges Qantil eine Punkt oder Grenze
in der Messreihe, wo x\% der Werte darunter liegen.

\[ \alpha: \text{ Prozentwert} \quad \alpha \in [0,1] \]
\[ x_1 - x_n \text{ sortiert nach grösse}  \]
\[ \alpha \cdot n \]
\[ \text{hier müssen 2 Fälle unterschieden werden: ganze Zahlen und gebrochene} \]
\[ \text{ganze Zahlen:} \quad \frac{1}{2} 
\cdot (x_{\alpha \cdot n} + x_{\alpha \cdot (n+1)}) \]
\[ \begin{array}{@{}@{}ll}
	\text{gebrochene Zahlen:} & k=\alpha \cdot n + \frac{1}{2} \\
	                          & k \text{ runden} \\
				  & \Rightarrow x_{(k)}
\end{array}\]

<<>>=
x<-round(x=runif(n=20, min=1, max=20), digits=0)
x<-sort(x)
x
quantile(x, prob=0.2)
quantile(x, prob=0.2, type=1)
quantile(x, prob=0.2, type=2)
@
Im obigen Beispiel wird mit R das 20\%-Quantil bestimmt. Hier ist aber 
Vorsicht geboten, denn R hat 9 verschiedene \verb!type! für die Funktion
\verb!quantile()! (default-Wert ist 7). Für uns aus dem 
Stochastik-Modul ist der \verb!type=2! 
der einzig richtige Wert!

\section{Median}
Der Median ist ein Spezialfall der Quantile, nämlich ist dies jenes Quantil,
welches die 50\%-Marke beschreibt.

Bsp.: Wir haben 5 Personen, und messen deren Höhe. Danach sortieren wir die
Ergebnisse. Der Median ist nun jene Person in der Mitte (unabhängig von seiner
genauen Höhe!). Interssant oder eben speziell am Median ist,
dass es immer die selbe Person bleibt auch wenn die kleineren und grösseren
noch grösser und noch kleiner werden. Dies bedeutet, dass der Median 
unempfindlich gegenüber sog. Ausreissern ist (denke an Durchschnittsvermögen
in einem Land mit vielen Armen und wenigen aber extrem Reichen).
<<>>=
x <- c(1.6, 1.7, 1.75, 1.87, 1.94)
median(x)
x <- c(1.2, 1.4, 1.75, 1.99, 2.14)
median(x)
@

\section{Varianz}
<<>>=
x=runif(n=10)
y=runif(n=10)
var(x)
@

\section{Kovarianz}
<<>>=
cov(x,y)
@

\section{Korrelationskoeffizient}
<<>>=
cor(x,y)
@

\section{Binomialverteilung}
Die Binomialverteilung kann bei Ereignissen eingesetzt werden, die zwei 
mögliche Ergebnisse zeigen können. 
\footnote{Beispiele für Ereignisse mit zwei möglichen Ergebnissen: 
  \begin{itemize} 
    \item Münzwurf $\Rightarrow$ Kopf $\leftrightarrow$ Zahl
    \item Würfeln $\Rightarrow$ Sechser $\leftrightarrow$ kein Sechser
  \end{itemize}}
Die Wahrscheinlichkeit ist dann wie folgt gegeben: 
\[ P(X=x) = 
\left( \begin{array}{c}n\\x\end{array} \right) \cdot p^x \cdot (1-p)^{n-x} 
= \frac{n!}{x! (n-x)!} \cdot p^x \cdot (1-p)^{n-x} \]
\begin{tabular}{@{}ll}
  $n$: & Anzahl Versuche \\
  $x$: & Anzahl Versuche mit positivem Ergebnis \\
  $p$: & Wahrscheinlichkeit für ein positives Ergebnis jedem einzelnen Versuch
\end{tabular} 
<<>>=
n=2;
x=1;
p=0.2;
dbinom(x=x,size=n,prob=p)
@


\section{Poissonverteilung}
Die Poissonverteilung wird bei Ereignissen verwendet, deren maximale Anzahl 
nicht begrenzt ist. Sie ist ein Grenzfall der Binomialverteilung. 
\[ P(X=x) = \exp(-\lambda) \cdot \frac{\lambda^x}{x!} \]
\begin{tabular}{@{}ll}
  $x$: & Anzahl Versuche mit positivem Ergebnis \\
  $\lambda$: & Erwartungswert
\end{tabular} 
<<>>=
lambda=2;
x=1;
dpois(x=x,lambda=lambda)
@